/*
public class DestinationData {
    void int main(){

        String[][] destinationArray =
                {Food, Bourbon N Toulouse,	Cajun,		829 Euclid Ave Lexington KY 40502},
                {Food, Gumbo Ya Ya,			Cajun,		1080 S Broadway #107 Lexington KY 40504},
                {Food, Joe Balonas,			Pizza,		120 W Maxwell St Lexington KY 40508},
                {Food, Tolly Ho,			Diner,		606 S Broadway Lexington KY 40508},
                {Food, Sawyers,			    Diner,		325 W Main St Lexington KY 40507},
                {Food, Ramseys,			    Diner,		151 W Zandale Dr Lexington KY 40503},
                {Food, Savs Grill,			African,	304 S Limestone Lexington KY 40508},
                {Food, Winchells,			Sports Bar,	348 Southland Dr Lexington KY 40503},
                {Food, Bad Wolf Burgers,	American,	350 Foreman Ave Lexington KY 40508},
                {Food, Saul Good,			American,	123 N Broadway Lexington KY 40507},
                {Food, Nats,				Thai,		111 S Upper St Lexington KY 40507},
                {Food, Old San Juan,		Cuban,		247 Surfside Dr Lexington KY 40503},
                {Food, Han Woo Ri,			Korean,		371 S Limestone Lexington KY 40508},
                {Food, Ramen Ya,			Japanese,	1030 S Broadway Lexington KY 40504},
                {Food, Malones,			    Steakhouse,	3347 Tates Creek Rd Lexington KY 40502},
                {Food, Bangkok House,		Thai,		275 Ave of Champions Lexington KY 40508},
                {Food, Joellas,			    Southern,	101 Cochran Rd Lexington KY 40502},
                {Food, Hibachi Express,	Japanese,	565 S Limestone Lexington KY 40508},
                {Food, Drakes,				American,	3347 Tates Creek Rd Lexington KY 40502},
                {Food, Canes,				Fast Food,	544 S Upper St Lexington KY 40508},
                {Food, Pazzos,				Pizza,		385 S Limestone Lexington KY 40508},

                {Drink, Two Keys,					Bar,			333 S Limestone Lexington KY 40508},
                {Drink, Country Boy,				Brewery,		436 Chair Ave Lexington KY 40508},
                {Drink, West 6th,					Brewery,		501 W 6th St #100 Lexington KY 40508},
                {Drink, Ethereal, 					Brewery,		1224 Manchester St Lexington KY 40504},
                {Drink, Charlie Browns,				Bar,			816 Euclid Ave Lexington KY 40502},
                {Drink, Tin Roof,					Bar,			303 S Limestone Lexington KY 40508},
                {Drink, The Beer Trappe,			Beer,			811 Euclid Ave Lexington KY 40502},
                {Drink, Best Friend Bar,			Bar,			500 Euclid Ave Lexington KY 40502},
                {Drink, Arcadium,					Barcade,		574 N Limestone Lexington KY 40508},
                {Drink, Stagger Inn,				Bar,			269 W Main St #50 Lexington KY 40507},
                {Drink, KSBar,						Sports Bar,		1030 S Broadway Lexington KY 40504},
                {Drink, McCarthys,					Pub,			117 S Upper St Lexington KY 40507},
                {Drink, The Ruddy Duck,				Bar,			131 Cheapside Lexington KY 40507},
                {Drink, Blue Stallion Brewing,		Brewery,		610 W 3rd St Lexington KY 40508},
                {Drink, Pivot Brewing,				Brewery,		1400 Delaware Ave Lexington KY 40505},
                {Drink, Henry Clays Public House,	Whiskey,		112 N Upper St Lexington KY 40507},
                {Drink, Paddock Bar,				Bar,			319 S Limestone # B Lexington KY 40508},
                {Drink, Shamrock Bar & Grille,		Pub,			4750 Hartland Pkwy #128 Lexington KY 40515},
                {Drink, Hop Cat,					Restaurant/Bar,	410 W Short St Lexington KY 40507},
                {Drink,	Bigg Blue Martini,			Hotel Bar,		369 W Vine St Lexington KY 40507},


                {Fun, Keeneland,						Horses,		4201 Versailles Rd Lexington KY 40510},
                {Fun, Rupp Arena,						Sports,		430 W Vine St Lexington KY 40507},
                {Fun, Kroger Field,						Sports,		1540 University Dr Lexington KY 40506},
                {Fun, Kentucky Theater,				Movies,		214 E Main St Lexington KY 40507},
                {Fun, Kentucky Horse Park,				Horses,		4089 Iron Works Pkwy Lexington KY 40511},
                {Fun, Red Mile,							Horses,		1200 Red Mile Rd Lexington KY 40504},
                {Fun, UK Aurboretum,					Park,		500 Alumni Dr Lexington KY 40503},
                {Fun, Triangle Park,					Park,		400 W Main St Lexington KY 40507},
                {Fun, Whitaker Bank Ballpark,			Sports,		207 Legends Ln Lexington KY 40505},
                {Fun, Bourbon Trail,					Distillery Tour	},
                {Fun, The Summit,						Shopping,	120 Summit At Fritz Farm #155 Lexington KY 40517},
                {Fun, Raven Run Nature Sanctuary,		Park,		3885 Raven Run Way Lexington KY 40515},
                {Fun, UK Art Museum,					Museum,		405 Rose St Lexington KY 40508},
                {Fun, Aviation Museum of Kentucky,		Museum,		4029 Airport Rd Lexington KY 40510},
                {Fun, Lexington Childrens Theatre,		Kids,		418 W Short St Lexington KY 40507},
                {Fun, Ashland: The Henry Clay Estate,	Museum,		120 Sycamore Rd Lexington KY 40502},
                {Fun, Mary Todd Lincoln House,			Museum,		578 W Main St Lexington KY 40507},
                {Fun, Breakout Games,					Escape Room,306 N Ashland Ave Lexington KY 40502},
                {Fun, Lexington Farmers Market,		Shopping,	249 W Main St Lexington KY 40507},
                {Fun, Lexington Ice Center,			Activity,	560 Eureka Springs Dr Lexington KY 40517},

     }
}
*/